ruta_csv: 'torrentdb.csv'
ruta_m3u_peliculas_get: 'peliculas_get.txt'
ruta_m3u_peliculas_base: 'peliculas_base.txt'
ruta_m3u_peliculas_horus: 'peliculas_horus.txt'
ruta_m3u_peliculas_torrserve: 'peliculas_torrserve.txt'
ruta_m3u_series_get: 'series_get.txt'
ruta_m3u_series_base: 'series_base.txt'
ruta_m3u_series_horus: 'series_horus.txt'
ruta_m3u_series_torrserve: 'series_torrserve.txt'
